package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"strings"

	"liteorm.org/cmd/sqlc-gen-liteorm/plugin"
	"liteorm.org/gen"
)

// options are the plugin's per-codegen settings, passed by sqlc as JSON in the
// GenerateRequest's plugin_options.
type options struct {
	Package  string `json:"package"`
	Filename string `json:"filename"`
}

// generate turns a sqlc GenerateRequest (parsed + typed queries) into a single
// Go file of liteorm-runtime query functions. Because sqlc has already inferred
// each query's result columns and parameter types from the schema catalog, the
// output is fully typed — no annotations needed, complementing the
// annotation-based generator in the gen package.
func generate(req *plugin.GenerateRequest) (*plugin.GenerateResponse, error) {
	var opt options
	if len(req.GetPluginOptions()) > 0 {
		_ = json.Unmarshal(req.GetPluginOptions(), &opt)
	}
	pkg := opt.Package
	if pkg == "" {
		pkg = "db"
	}
	name := opt.Filename
	if name == "" {
		name = "query.liteorm.go"
	}

	src, err := emit(pkg, req.GetQueries())
	if err != nil {
		return nil, err
	}
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return nil, fmt.Errorf("sqlc-gen-liteorm: formatting output: %w\n%s", err, src)
	}
	return &plugin.GenerateResponse{
		Files: []*plugin.File{{Name: name, Contents: formatted}},
	}, nil
}

func emit(pkg string, queries []*plugin.Query) (string, error) {
	var body strings.Builder
	needQuery, needErrors, needTime := false, false, false

	for _, q := range queries {
		cmd := gen.QueryCmd(strings.TrimPrefix(q.GetCmd(), ":")) // sqlc cmds are ":one"/":many"/…

		// Result type: a generated row struct for multi-column reads, a scalar
		// for one. A zero-column :one/:many is degenerate — treat it as :exec.
		result := ""
		if cmd == gen.CmdOne || cmd == gen.CmdMany {
			cols := q.GetColumns()
			switch len(cols) {
			case 0:
				cmd = gen.CmdExec
			case 1:
				result, needTime = goType(cols[0], needTime)
			default:
				rowName := q.GetName() + "Row"
				emitRowStruct(&body, rowName, cols, &needTime)
				result = rowName
			}
		}
		if gen.NeedsQueryImport(cmd, result) {
			needQuery = true
		}
		if cmd == gen.CmdExecLastID {
			needErrors = true
		}

		constName := gen.LowerFirst(q.GetName()) + "SQL"
		fmt.Fprintf(&body, "const %s = `%s`\n\n", constName, strings.TrimSpace(q.GetText()))

		// Parameters → typed args.
		var params, callArgs strings.Builder
		params.WriteString("ctx context.Context, sess liteorm.Session")
		for i, p := range q.GetParams() {
			an := argName(p, i)
			at, nt := goType(p.GetColumn(), needTime)
			needTime = nt
			fmt.Fprintf(&params, ", %s %s", an, at)
			callArgs.WriteString(", ")
			callArgs.WriteString(an)
		}
		gen.EmitFunc(&body, q.GetName(), cmd, constName, result, params.String(), callArgs.String())
	}

	var h strings.Builder
	h.WriteString("// Code generated by sqlc-gen-liteorm. DO NOT EDIT.\n\n")
	fmt.Fprintf(&h, "package %s\n\n", pkg)
	h.WriteString("import (\n\t\"context\"\n")
	if needErrors {
		h.WriteString("\t\"errors\"\n")
	}
	if needTime {
		h.WriteString("\t\"time\"\n")
	}
	h.WriteString("\n\tliteorm \"liteorm.org\"\n")
	if needQuery {
		h.WriteString("\t\"liteorm.org/query\"\n")
	}
	h.WriteString(")\n\n")
	h.WriteString(body.String())
	return h.String(), nil
}

func emitRowStruct(b *strings.Builder, name string, cols []*plugin.Column, needTime *bool) {
	fmt.Fprintf(b, "type %s struct {\n", name)
	for _, c := range cols {
		gt, nt := goType(c, *needTime)
		*needTime = nt
		fmt.Fprintf(b, "\t%s %s `db:%q`\n", gen.GoName(c.GetName()), gt, c.GetName())
	}
	b.WriteString("}\n\n")
}

func argName(p *plugin.Parameter, i int) string {
	if c := p.GetColumn(); c != nil && c.GetName() != "" {
		return lowerCamel(c.GetName())
	}
	return fmt.Sprintf("arg%d", i+1)
}
