// Code generated by liteorm gen. DO NOT EDIT.

package main

import (
	"context"
	"errors"

	liteorm "liteorm.org"
	"liteorm.org/query"
)

const insertUserSQL = `INSERT INTO users (name, email, active, last_seen) VALUES (?, ?, ?, ?)`

func InsertUser(ctx context.Context, sess liteorm.Session, name string, email string, active int, lastSeen string) (int64, error) {
	res, err := sess.ExecContext(ctx, insertUserSQL, name, email, active, lastSeen)
	if err != nil {
		return 0, err
	}
	li, ok := res.(liteorm.LastInsertIder)
	if !ok {
		return 0, errors.New("liteorm: backend does not report LastInsertId")
	}
	return li.LastInsertId()
}

const getUserSQL = `SELECT id, name, email, active, last_seen FROM users WHERE id = ?`

func GetUser(ctx context.Context, sess liteorm.Session, id int64) (User, error) {
	var zero User
	rows, err := query.Raw[User](ctx, sess, getUserSQL, id)
	if err != nil {
		return zero, err
	}
	if len(rows) == 0 {
		return zero, liteorm.ErrNoRows
	}
	return rows[0], nil
}

const listActiveSQL = `SELECT id, name, email, active, last_seen FROM users WHERE active = ? ORDER BY name`

func ListActive(ctx context.Context, sess liteorm.Session, active bool) ([]User, error) {
	return query.Raw[User](ctx, sess, listActiveSQL, active)
}

const countUsersSQL = `SELECT count(*) FROM users`

func CountUsers(ctx context.Context, sess liteorm.Session) (int64, error) {
	var zero int64
	rows, err := sess.QueryContext(ctx, countUsersSQL)
	if err != nil {
		return zero, err
	}
	defer func() { _ = rows.Close() }()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return zero, err
		}
		return zero, liteorm.ErrNoRows
	}
	if err := rows.Scan(&zero); err != nil {
		return zero, err
	}
	return zero, nil
}

const deactivateSQL = `UPDATE users SET active = 0 WHERE id = ?`

func Deactivate(ctx context.Context, sess liteorm.Session, id int64) error {
	_, err := sess.ExecContext(ctx, deactivateSQL, id)
	return err
}

const purgeStaleSQL = `DELETE FROM users WHERE last_seen < ?`

func PurgeStale(ctx context.Context, sess liteorm.Session, before string) (int64, error) {
	res, err := sess.ExecContext(ctx, purgeStaleSQL, before)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected(), nil
}
